### ISSUE TITLE
Installation requires superuser privileges?

### ISSUE THREAD

**Issue by T1mK** [alex1701c/JetBrainsDolphinPlugin#5]
During the install process, it suddenly asked to enter credentials for superuser access. Since this is a service menu extension for my user account, I found it suspicious, and therefore would like to know for what purpose superuser access is needed, and if that could be modified so that the install stays within the privilege boundaries of the installing user?

Thanks for your time and creating this service menu extension!

**Comment by alex1701c** [comment]
>I found it suspicious, and therefore would like to know for what purpose superuser access is needed

By default, Qt only looks for plugins in the /usr location. Because this service menu installs a C++ plugin, we need this install location to make it work out of the box. 

Please also see this section from the README "Option B: Build from source using installer script (without admin privileges)".
Due to the plugin path issue I explained above, the following code is executed there:
```bash
# Add the installation path to the QT_PLUGIN_PATH
if [[ -z "${QT_PLUGIN_PATH}" || "${QT_PLUGIN_PATH}" != *".local/lib/qt/plugins/"* ]]; then
    echo "export QT_PLUGIN_PATH=~/.local/lib/qt/plugins/:$QT_PLUGIN_PATH" >> ~/.bashrc
    export QT_PLUGIN_PATH=~/.local/lib/qt/plugins/:$QT_PLUGIN_PATH
fi
```
This is a bit hacky, because there are other shells like fish which are not taken into account by this. Because of that, I recommend installing the file in /usr.

Would maybe an extra line of output, explaining why the "**sudo** make install" is needed in one sentence, be good enough for you?

**Comment by T1mK** [comment]
Hi there, thanks a lot for considering and replying to the issue :smile: 

> Would maybe an extra line of output, explaining why the "sudo make install" is needed in one sentence, be good enough for you?

Yes, this is certainly more transparent and shows that it was deliberate. Thank you!

I looked around a bit to get a better understanding of where Qt puts plugins and ways of changing their location. What you do you in your "Option B" script appears to be the easiest, if not the only, way of getting Qt plugins installed without some type of modification that would otherwise require superuser privileges. 

For reference and maybe to enlighten others out there reading this issue, here are two links I found especially useful: 

- https://www.tripleboot.org/?p=536#PluginDLLs
- https://forum.qt.io/topic/58499/solved-problems-with-setting-paths-to-libs-and-plugins-in-qt-app-s-executable-file/3
- https://doc.qt.io/qt-6/deployment-plugins.html

Thanks again and enjoy the end-of-the-year festivities :snowman_with_snow: :tada:

**Comment by alex1701c** [comment]
I have added a message to the install script. Thanks for your feedback :)
